import * as Lucide from 'lucide-react-native';
import { Feather } from '@expo/vector-icons';
import { 
  Scissors, 
  Sparkles, 
  Hand, 
  Footprints,
  Droplet,
  Bath,
  Sun,
  Snowflake,
  Thermometer,
  Wind,
  ShoppingCart,
  Trash2,
  ChefHat,
  Home,
  Briefcase,
  GraduationCap,
  Users,
  Car,
  Dumbbell,
  Film,
  Trees,
  Palmtree,
  Clock,
  ListChecks,
  Target,
  Coffee,
  Heart as LucideHeart,
  Ear,
  DollarSign,
  Music,
  Gamepad2,
  Dog,
  Camera,
  Palette,
  Paintbrush,
  Pen,
  BookOpen,
  Puzzle,
  Bike,
  Flower2,
  Cake,
  Fish,
  Tent,
  Mic,
  Guitar,
  Drama,
  Bed,
  MessageCircle,
  Utensils,
  Activity,
  Mountain,
  Smile,
  TrendingUp,
  PersonStanding,
  Footprints as Walking,
  Shuffle,
  Package,
  Archive,
  Scan,
  Notebook,
  PenTool,
  Globe,
  Monitor,
  Package2,
  Calendar as CalendarIcon,
  Stethoscope,
  AlertCircle,
  XCircle,
  Hammer,
  Waves,
  Layers,
  Scissors as CuttingIcon,
} from 'lucide-react-native';

// Fallback icon components when specific Lucide icons are not available at runtime
const CloudIcon = (Lucide as any).Cloud ?? ((props: any) => <Feather name="cloud" {...props} />);
const CloudRainIcon = (Lucide as any).CloudRain ?? ((props: any) => <Feather name="cloud-rain" {...props} />);
const CloudLightningIcon = (Lucide as any).CloudLightning ?? ((props: any) => <Feather name="cloud-lightning" {...props} />);

export type ActivityIconName = keyof typeof activityIconMap;

export const activityIconMap = {
  // Beauty
  haircut: Scissors,
  wellness: Sparkles,
  massage: Hand,
  manicure: Hand,
  pedicure: Footprints,
  skincare: Droplet,
  spa: Bath,
  
  // Weather
  sunny: Sun,
  clouds: CloudIcon,
  rain: CloudRainIcon,
  snow: Snowflake,
  heat: Thermometer,
  storm: CloudLightningIcon,
  wind: Wind,
  
  // Chores
  shopping: ShoppingCart,
  cleaning: Trash2,
  cooking: ChefHat,
  laundry: Droplet,
  'dust-removal': Sparkles,
  'empty-trash': Trash2,
  handwashing: Hand,
  'wipe-off': Sparkles,
  'set-schedule': Clock,
  'maximize-storage': Archive,
  
  // Daily Routines
  sleep: Bed,
  workout: Dumbbell,
  'drink-water': Droplet,
  coffee: Coffee,
  work: Briefcase,
  meal: Utensils,
  chatting: MessageCircle,
  reading: BookOpen,
  
  // Sports & Activities
  stroll: Walking,
  hiking: Mountain,
  'jump-rope': Activity,
  jogging: TrendingUp,
  'tai-chi': PersonStanding,
  yoga: PersonStanding,
  gym: Dumbbell,
  sport: Activity,
  
  // Hobby
  travel: Car,
  music: Music,
  game: Gamepad2,
  movies: Film,
  pets: Dog,
  diy: Hammer,
  dance: Smile,
  photography: Camera,
  drawing: Pen,
  'board-game': Gamepad2,
  painting: Palette,
  crafting: CuttingIcon,
  knitting: Feather,
  gardening: Flower2,
  'cooking-hobby': ChefHat,
  baking: Cake,
  writing: PenTool,
  blogging: Globe,
  'video-games': Monitor,
  puzzles: Puzzle,
  collecting: Package2,
  fishing: Fish,
  camping: Tent,
  cycling: Bike,
  skateboarding: Activity,
  singing: Mic,
  'playing-instrument': Guitar,
  theater: Drama,
  pottery: Waves,
  origami: Layers,
  
  // Places
  home: Home,
  'work-place': Briefcase,
  school: GraduationCap,
  visit: Users,
  cinema: Film,
  nature: Trees,
  vacation: Palmtree,
  
  // Health
  period: CalendarIcon,
  checkup: Stethoscope,
  pain: AlertCircle,
  'put-it-off': XCircle,
  
  // Productivity
  'start-early': Clock,
  'make-list': ListChecks,
  focus: Target,
  'take-break': Coffee,
  
  // Better Me
  meditation: Sparkles,
  kindness: LucideHeart,
  listen: Ear,
  donate: DollarSign,
  'practice-force': Sparkles,
};

export const getActivityIcon = (activityId: string) => {
  return activityIconMap[activityId as ActivityIconName] || Sparkles;
};
